export const dummyData = {
  kind: "youtube#playlistItemListResponse",
  etag: "9GcIGebK_AnGpzYwQFZ_A0nuREc",
  nextPageToken: "EAAaBlBUOkNBbw",
  items: [
    {
      kind: "youtube#playlistItem",
      etag: "efIRz0Z3DwcGFFL3pDGIxav2fmE",
      id: "UExSQnAwRmUyR3BnbWdvc2NORkx4TnlCVlNGVmRZbUZrcS41NkI0NEY2RDEwNTU3Q0M2",
      snippet: {
        publishedAt: "2020-09-03T10:04:11Z",
        channelId: "UC_aEa8K-EOJ3D6gOs7HcyNg",
        title: "The Revolution",
        description:
          "Provided to YouTube by AEI Group Ltd\n\nThe Revolution · Egzod · Neoni\n\nThe Revolution\n\n℗ 2020 NCS\n\nReleased on: 2020-09-03\n\nComposer: Caitlin Aureal Powell\nComposer: Carlos Carvalho Martins\nComposer: Sidney Dior Powell\n\nAuto-generated by YouTube.",
        thumbnails: {
          default: {
            url: "https://i.ytimg.com/vi/AMSV7I69IzM/default.jpg",
            width: 120,
            height: 90
          },
          medium: {
            url: "https://i.ytimg.com/vi/AMSV7I69IzM/mqdefault.jpg",
            width: 320,
            height: 180
          },
          high: {
            url: "https://i.ytimg.com/vi/AMSV7I69IzM/hqdefault.jpg",
            width: 480,
            height: 360
          },
          standard: {
            url: "https://i.ytimg.com/vi/AMSV7I69IzM/sddefault.jpg",
            width: 640,
            height: 480
          },
          maxres: {
            url: "https://i.ytimg.com/vi/AMSV7I69IzM/maxresdefault.jpg",
            width: 1280,
            height: 720
          }
        },
        channelTitle: "NoCopyrightSounds",
        playlistId: "PLRBp0Fe2GpgmgoscNFLxNyBVSFVdYmFkq",
        position: 0,
        resourceId: {
          kind: "youtube#video",
          videoId: "AMSV7I69IzM"
        },
        videoOwnerChannelTitle: "Egzod - Topic",
        videoOwnerChannelId: "UCGgeiSMVvdO6xpCRtA7P9Rg"
      }
    },
    {
      kind: "youtube#playlistItem",
      etag: "JVnnDBPg7kYfg7PKJqItLh4gSGk",
      id: "UExSQnAwRmUyR3BnbWdvc2NORkx4TnlCVlNGVmRZbUZrcS4yODlGNEE0NkRGMEEzMEQy",
      snippet: {
        publishedAt: "2020-09-03T10:04:11Z",
        channelId: "UC_aEa8K-EOJ3D6gOs7HcyNg",
        title: "Goodbye",
        description:
          "Provided to YouTube by AEI Group Ltd\n\nGoodbye · Linko\n\nGoodbye\n\n℗ 2020 NCS\n\nReleased on: 2020-08-18\n\nComposer: Vetle Riis Jacobsen\n\nAuto-generated by YouTube.",
        thumbnails: {
          default: {
            url: "https://i.ytimg.com/vi/LgAkvynF2UE/default.jpg",
            width: 120,
            height: 90
          },
          medium: {
            url: "https://i.ytimg.com/vi/LgAkvynF2UE/mqdefault.jpg",
            width: 320,
            height: 180
          },
          high: {
            url: "https://i.ytimg.com/vi/LgAkvynF2UE/hqdefault.jpg",
            width: 480,
            height: 360
          },
          standard: {
            url: "https://i.ytimg.com/vi/LgAkvynF2UE/sddefault.jpg",
            width: 640,
            height: 480
          },
          maxres: {
            url: "https://i.ytimg.com/vi/LgAkvynF2UE/maxresdefault.jpg",
            width: 1280,
            height: 720
          }
        },
        channelTitle: "NoCopyrightSounds",
        playlistId: "PLRBp0Fe2GpgmgoscNFLxNyBVSFVdYmFkq",
        position: 1,
        resourceId: {
          kind: "youtube#video",
          videoId: "LgAkvynF2UE"
        },
        videoOwnerChannelTitle: "Linko - Topic",
        videoOwnerChannelId: "UCvtNnGO-6U_I6VRXzODw3FQ"
      }
    },
    {
      kind: "youtube#playlistItem",
      etag: "V-9A471ELepLc0FM3KqDyNKn01o",
      id: "UExSQnAwRmUyR3BnbWdvc2NORkx4TnlCVlNGVmRZbUZrcS4wMTcyMDhGQUE4NTIzM0Y5",
      snippet: {
        publishedAt: "2020-09-03T10:04:12Z",
        channelId: "UC_aEa8K-EOJ3D6gOs7HcyNg",
        title: "Slow Down",
        description:
          "Provided to YouTube by AEI Group Ltd\n\nSlow Down · Chris Linton · Cadmium\n\nSlow Down\n\n℗ 2020 NCS\n\nReleased on: 2020-08-14\n\nComposer: Alexander Clark\n\nAuto-generated by YouTube.",
        thumbnails: {
          default: {
            url: "https://i.ytimg.com/vi/bf4vvK9xv98/default.jpg",
            width: 120,
            height: 90
          },
          medium: {
            url: "https://i.ytimg.com/vi/bf4vvK9xv98/mqdefault.jpg",
            width: 320,
            height: 180
          },
          high: {
            url: "https://i.ytimg.com/vi/bf4vvK9xv98/hqdefault.jpg",
            width: 480,
            height: 360
          },
          standard: {
            url: "https://i.ytimg.com/vi/bf4vvK9xv98/sddefault.jpg",
            width: 640,
            height: 480
          },
          maxres: {
            url: "https://i.ytimg.com/vi/bf4vvK9xv98/maxresdefault.jpg",
            width: 1280,
            height: 720
          }
        },
        channelTitle: "NoCopyrightSounds",
        playlistId: "PLRBp0Fe2GpgmgoscNFLxNyBVSFVdYmFkq",
        position: 2,
        resourceId: {
          kind: "youtube#video",
          videoId: "bf4vvK9xv98"
        },
        videoOwnerChannelTitle: "Chris Linton - Topic",
        videoOwnerChannelId: "UCytodNSjtXX9M5YRe4vbA2Q"
      }
    },
    {
      kind: "youtube#playlistItem",
      etag: "5TYe1odnWJMbHqnmbRVWMUX62Ro",
      id: "UExSQnAwRmUyR3BnbWdvc2NORkx4TnlCVlNGVmRZbUZrcS41MjE1MkI0OTQ2QzJGNzNG",
      snippet: {
        publishedAt: "2020-09-03T10:04:12Z",
        channelId: "UC_aEa8K-EOJ3D6gOs7HcyNg",
        title: "Happi",
        description:
          "Provided to YouTube by AEI Group Ltd\n\nHappi · Mangoo · bby ivy\n\nHappi\n\n℗ 2020 NCS\n\nReleased on: 2020-07-24\n\nComposer: Helge Reinsnes Moen\nComposer: Jim Bergsted\nComposer: Mattias Brånn\nComposer: Robert Gasser\nComposer: Viktoria Reitan\n\nAuto-generated by YouTube.",
        thumbnails: {
          default: {
            url: "https://i.ytimg.com/vi/LoCsFjf7xGA/default.jpg",
            width: 120,
            height: 90
          },
          medium: {
            url: "https://i.ytimg.com/vi/LoCsFjf7xGA/mqdefault.jpg",
            width: 320,
            height: 180
          },
          high: {
            url: "https://i.ytimg.com/vi/LoCsFjf7xGA/hqdefault.jpg",
            width: 480,
            height: 360
          },
          standard: {
            url: "https://i.ytimg.com/vi/LoCsFjf7xGA/sddefault.jpg",
            width: 640,
            height: 480
          },
          maxres: {
            url: "https://i.ytimg.com/vi/LoCsFjf7xGA/maxresdefault.jpg",
            width: 1280,
            height: 720
          }
        },
        channelTitle: "NoCopyrightSounds",
        playlistId: "PLRBp0Fe2GpgmgoscNFLxNyBVSFVdYmFkq",
        position: 3,
        resourceId: {
          kind: "youtube#video",
          videoId: "LoCsFjf7xGA"
        },
        videoOwnerChannelTitle: "Mangoo - Topic",
        videoOwnerChannelId: "UCtsdavZDmHkrIpmaakaSWjA"
      }
    },
    {
      kind: "youtube#playlistItem",
      etag: "JC9Ie00ClmY9bq7q1oR5GJCA69c",
      id: "UExSQnAwRmUyR3BnbWdvc2NORkx4TnlCVlNGVmRZbUZrcS4wOTA3OTZBNzVEMTUzOTMy",
      snippet: {
        publishedAt: "2020-09-03T10:04:13Z",
        channelId: "UC_aEa8K-EOJ3D6gOs7HcyNg",
        title: "Slow",
        description:
          "Provided to YouTube by AEI Group Ltd\n\nSlow · Diviners · Riell\n\nSlow\n\n℗ 2020 NCS\n\nReleased on: 2020-08-06\n\nComposer: Kamil Mateusz Pankowski\nComposer: Kamil Piotr Relikowski\nComposer: Maria Elizabeth Phillipos\n\nAuto-generated by YouTube.",
        thumbnails: {
          default: {
            url: "https://i.ytimg.com/vi/2lAlOTtN15w/default.jpg",
            width: 120,
            height: 90
          },
          medium: {
            url: "https://i.ytimg.com/vi/2lAlOTtN15w/mqdefault.jpg",
            width: 320,
            height: 180
          },
          high: {
            url: "https://i.ytimg.com/vi/2lAlOTtN15w/hqdefault.jpg",
            width: 480,
            height: 360
          },
          standard: {
            url: "https://i.ytimg.com/vi/2lAlOTtN15w/sddefault.jpg",
            width: 640,
            height: 480
          },
          maxres: {
            url: "https://i.ytimg.com/vi/2lAlOTtN15w/maxresdefault.jpg",
            width: 1280,
            height: 720
          }
        },
        channelTitle: "NoCopyrightSounds",
        playlistId: "PLRBp0Fe2GpgmgoscNFLxNyBVSFVdYmFkq",
        position: 4,
        resourceId: {
          kind: "youtube#video",
          videoId: "2lAlOTtN15w"
        },
        videoOwnerChannelTitle: "Diviners - Topic",
        videoOwnerChannelId: "UC82TPvdhltkCjtKBlO74wYQ"
      }
    },
    {
      kind: "youtube#playlistItem",
      etag: "ZoVzKhKXV5EmuCfuaf40hpGjtG4",
      id: "UExSQnAwRmUyR3BnbWdvc2NORkx4TnlCVlNGVmRZbUZrcS4xMkVGQjNCMUM1N0RFNEUx",
      snippet: {
        publishedAt: "2020-09-03T10:04:14Z",
        channelId: "UC_aEa8K-EOJ3D6gOs7HcyNg",
        title: "23",
        description:
          "Provided to YouTube by AEI Group Ltd\n\n23 · Diamond Eyes\n\n23\n\n℗ 2020 NCS\n\nReleased on: 2020-07-17\n\nProducer: Joshua Michael Marment\nComposer: Joshua Michael Marment\n\nAuto-generated by YouTube.",
        thumbnails: {
          default: {
            url: "https://i.ytimg.com/vi/YPyC2Dmjeaw/default.jpg",
            width: 120,
            height: 90
          },
          medium: {
            url: "https://i.ytimg.com/vi/YPyC2Dmjeaw/mqdefault.jpg",
            width: 320,
            height: 180
          },
          high: {
            url: "https://i.ytimg.com/vi/YPyC2Dmjeaw/hqdefault.jpg",
            width: 480,
            height: 360
          },
          standard: {
            url: "https://i.ytimg.com/vi/YPyC2Dmjeaw/sddefault.jpg",
            width: 640,
            height: 480
          },
          maxres: {
            url: "https://i.ytimg.com/vi/YPyC2Dmjeaw/maxresdefault.jpg",
            width: 1280,
            height: 720
          }
        },
        channelTitle: "NoCopyrightSounds",
        playlistId: "PLRBp0Fe2GpgmgoscNFLxNyBVSFVdYmFkq",
        position: 5,
        resourceId: {
          kind: "youtube#video",
          videoId: "YPyC2Dmjeaw"
        },
        videoOwnerChannelTitle: "Diamond Eyes - Topic",
        videoOwnerChannelId: "UCWxTPUxNQJyIdODN_VQIMmg"
      }
    },
    {
      kind: "youtube#playlistItem",
      etag: "2jz6U1PvldGYlJY1G0DGtxci6mU",
      id: "UExSQnAwRmUyR3BnbWdvc2NORkx4TnlCVlNGVmRZbUZrcS41MzJCQjBCNDIyRkJDN0VD",
      snippet: {
        publishedAt: "2020-09-03T10:04:15Z",
        channelId: "UC_aEa8K-EOJ3D6gOs7HcyNg",
        title: "Murderer",
        description:
          "Provided to YouTube by AEI Group Ltd\n\nMurderer · CARBIN · Hayve · Emily Makis\n\nMurderer\n\n℗ 2020 NCS\n\nReleased on: 2020-08-25\n\nComposer: Aaro Haapanen\nComposer: Emily Makis\nComposer: McKenzie Morrow\nComposer: Omer Morad\nComposer: Tatu Lemetti\n\nAuto-generated by YouTube.",
        thumbnails: {
          default: {
            url: "https://i.ytimg.com/vi/TB-B14dlJmk/default.jpg",
            width: 120,
            height: 90
          },
          medium: {
            url: "https://i.ytimg.com/vi/TB-B14dlJmk/mqdefault.jpg",
            width: 320,
            height: 180
          },
          high: {
            url: "https://i.ytimg.com/vi/TB-B14dlJmk/hqdefault.jpg",
            width: 480,
            height: 360
          },
          standard: {
            url: "https://i.ytimg.com/vi/TB-B14dlJmk/sddefault.jpg",
            width: 640,
            height: 480
          },
          maxres: {
            url: "https://i.ytimg.com/vi/TB-B14dlJmk/maxresdefault.jpg",
            width: 1280,
            height: 720
          }
        },
        channelTitle: "NoCopyrightSounds",
        playlistId: "PLRBp0Fe2GpgmgoscNFLxNyBVSFVdYmFkq",
        position: 6,
        resourceId: {
          kind: "youtube#video",
          videoId: "TB-B14dlJmk"
        },
        videoOwnerChannelTitle: "Carbin - Topic",
        videoOwnerChannelId: "UCxt_hvceDeyjK1NwbyaIhvw"
      }
    },
    {
      kind: "youtube#playlistItem",
      etag: "rgKJUIjWY22fLSeLjFimFBMufRE",
      id: "UExSQnAwRmUyR3BnbWdvc2NORkx4TnlCVlNGVmRZbUZrcS5DQUNERDQ2NkIzRUQxNTY1",
      snippet: {
        publishedAt: "2020-09-03T10:04:15Z",
        channelId: "UC_aEa8K-EOJ3D6gOs7HcyNg",
        title: "See You at the End",
        description:
          "Provided to YouTube by AEI Group Ltd\n\nSee You at the End · Abandoned · InfiNoise · Mendum · Brenton Mattheus\n\nSee You at the End\n\n℗ 2020 NCS\n\nReleased on: 2020-09-01\n\nComposer: Amir hosein Khast Khodaie\nComposer: Benjamin Felix Meyer\nComposer: Brenton Mattheus\nComposer: Hamid Reza Akbari\nComposer: Leon Herbert Viljem Mekschrat\n\nAuto-generated by YouTube.",
        thumbnails: {
          default: {
            url: "https://i.ytimg.com/vi/h1vAnYt-qTs/default.jpg",
            width: 120,
            height: 90
          },
          medium: {
            url: "https://i.ytimg.com/vi/h1vAnYt-qTs/mqdefault.jpg",
            width: 320,
            height: 180
          },
          high: {
            url: "https://i.ytimg.com/vi/h1vAnYt-qTs/hqdefault.jpg",
            width: 480,
            height: 360
          },
          standard: {
            url: "https://i.ytimg.com/vi/h1vAnYt-qTs/sddefault.jpg",
            width: 640,
            height: 480
          },
          maxres: {
            url: "https://i.ytimg.com/vi/h1vAnYt-qTs/maxresdefault.jpg",
            width: 1280,
            height: 720
          }
        },
        channelTitle: "NoCopyrightSounds",
        playlistId: "PLRBp0Fe2GpgmgoscNFLxNyBVSFVdYmFkq",
        position: 7,
        resourceId: {
          kind: "youtube#video",
          videoId: "h1vAnYt-qTs"
        },
        videoOwnerChannelTitle: "Abandoned - Topic",
        videoOwnerChannelId: "UCxhhUcf_c0oWZbALdPwmljg"
      }
    },
    {
      kind: "youtube#playlistItem",
      etag: "JzRCMcbz_5e1ZEjdteR0b4xv1NU",
      id: "UExSQnAwRmUyR3BnbWdvc2NORkx4TnlCVlNGVmRZbUZrcS45NDk1REZENzhEMzU5MDQz",
      snippet: {
        publishedAt: "2020-09-03T10:04:16Z",
        channelId: "UC_aEa8K-EOJ3D6gOs7HcyNg",
        title: "Afterlife",
        description:
          "Provided to YouTube by AEI Group Ltd\n\nAfterlife · Besomorph · EMM\n\nAfterlife\n\n℗ 2020 NCS\n\nReleased on: 2020-08-21\n\nComposer: Bessam Witwit\nComposer: Elijah Weinkauf\nComposer: Emma Norris\n\nAuto-generated by YouTube.",
        thumbnails: {
          default: {
            url: "https://i.ytimg.com/vi/s1qFKJ4CHVI/default.jpg",
            width: 120,
            height: 90
          },
          medium: {
            url: "https://i.ytimg.com/vi/s1qFKJ4CHVI/mqdefault.jpg",
            width: 320,
            height: 180
          },
          high: {
            url: "https://i.ytimg.com/vi/s1qFKJ4CHVI/hqdefault.jpg",
            width: 480,
            height: 360
          },
          standard: {
            url: "https://i.ytimg.com/vi/s1qFKJ4CHVI/sddefault.jpg",
            width: 640,
            height: 480
          },
          maxres: {
            url: "https://i.ytimg.com/vi/s1qFKJ4CHVI/maxresdefault.jpg",
            width: 1280,
            height: 720
          }
        },
        channelTitle: "NoCopyrightSounds",
        playlistId: "PLRBp0Fe2GpgmgoscNFLxNyBVSFVdYmFkq",
        position: 8,
        resourceId: {
          kind: "youtube#video",
          videoId: "s1qFKJ4CHVI"
        },
        videoOwnerChannelTitle: "Besomorph - Topic",
        videoOwnerChannelId: "UC1l-Ye7e4fDV73K8P2tRuIw"
      }
    },
    {
      kind: "youtube#playlistItem",
      etag: "C6SZePDDhwmmD1J8aOUcL9zFTXo",
      id: "UExSQnAwRmUyR3BnbWdvc2NORkx4TnlCVlNGVmRZbUZrcS5GNjNDRDREMDQxOThCMDQ2",
      snippet: {
        publishedAt: "2020-09-03T10:04:16Z",
        channelId: "UC_aEa8K-EOJ3D6gOs7HcyNg",
        title: "Be Myself",
        description:
          "Provided to YouTube by AEI Group Ltd\n\nBe Myself · Tom Wilson\n\nBe Myself\n\n℗ 2020 NCS\n\nReleased on: 2020-08-27\n\nComposer: Thomas Wilson\n\nAuto-generated by YouTube.",
        thumbnails: {
          default: {
            url: "https://i.ytimg.com/vi/c2Q2ZbN6onU/default.jpg",
            width: 120,
            height: 90
          },
          medium: {
            url: "https://i.ytimg.com/vi/c2Q2ZbN6onU/mqdefault.jpg",
            width: 320,
            height: 180
          },
          high: {
            url: "https://i.ytimg.com/vi/c2Q2ZbN6onU/hqdefault.jpg",
            width: 480,
            height: 360
          },
          standard: {
            url: "https://i.ytimg.com/vi/c2Q2ZbN6onU/sddefault.jpg",
            width: 640,
            height: 480
          },
          maxres: {
            url: "https://i.ytimg.com/vi/c2Q2ZbN6onU/maxresdefault.jpg",
            width: 1280,
            height: 720
          }
        },
        channelTitle: "NoCopyrightSounds",
        playlistId: "PLRBp0Fe2GpgmgoscNFLxNyBVSFVdYmFkq",
        position: 9,
        resourceId: {
          kind: "youtube#video",
          videoId: "c2Q2ZbN6onU"
        },
        videoOwnerChannelTitle: "Tom Wilson - Topic",
        videoOwnerChannelId: "UCjZPu5m-_abFyy9Qc9PmQgg"
      }
    }
  ],
  pageInfo: {
    totalResults: 252,
    resultsPerPage: 10
  }
};
